### ISSUE TITLE
Whisper on webGPU?

### ISSUE THREAD

**Issue by sandorkonya** [huggingface/transformers.js#100]
Somewhat related to [this thread](https://github.com/xenova/transformers.js/issues/20). 

Is it within scope to implement a webGPU accelerated version of Whisper?

Not sure if this helps, but there is a [C port for Whisper wirh CPU implementation](https://github.com/ggerganov/whisper.cpp), and as mentioned in [this discussion](https://github.com/ggerganov/whisper.cpp/discussions/126), the main thing that needs to be offloaded to the GPU is the GGML_OP_MUL_MAT operator.

**Comment by DK013** [comment]
> Is it within scope to implement a webGPU accelerated version of Whisper?

As I understand, it's simply a matter of changing the Execution provider now to JSEP. The C++ port uses GGML format for the model and this repo uses onnx models alongside onnxruntime to run infrence. Both implementations are different. And with the WebGPU support for onnxruntime (check this PR: [js/web] WebGPU backend via JSEP [#14579](https://github.com/microsoft/onnxruntime/pull/14579)) which was merged today and official release build will come soon enough, I believe we don't have to worry about CUDA or DirectML endpoints, JSEP does the work for us. It's only a matter of updating the onncruntime dependency and using JSEP for execution provider.

@xenova correct me if I'm wrong.

**Comment by xenova** [comment]
> > Is it within scope to implement a webGPU accelerated version of Whisper?
> 
> 
> 
> As I understand, it's simply a matter of changing the Execution provider now to JSEP. The C++ port uses GGML format for the model and this repo uses onnx models alongside onnxruntime to run infrence. Both implementations are different. And with the WebGPU support for onnxruntime (check this PR: [js/web] WebGPU backend via JSEP [#14579](https://github.com/microsoft/onnxruntime/pull/14579)) which was merged today and official release build will come soon enough, I believe we don't have to worry about CUDA or DirectML endpoints, JSEP does the work for us. It's only a matter of updating the onnxruntime dependency and using JSEP for execution provider.
> 
> 
> 
> @xenova correct me if I'm wrong.

Yep, that's correct! It should be as simple as changing the execution provided to `webgpu` (vs. `wasm`)

**Comment by drcodecamp** [comment]
@xenova how we can use gpu power when we use nodejs ?

i try to build a local server with node, all works but very slow on an AMD 5950X , i would like to use my RTX 4070TI 
to transcribe but i couldnt find any document that talks about it

**Comment by Dolidodzik** [comment]
@xenova, are there any news? Will we be allowed to use webgpu with transformers.js any time soon?

**Comment by gabrielgrant** [comment]
thanks for the update @guschmue ! 

Is there a GH issue for the problem you're describing? Is it this? https://github.com/microsoft/onnxruntime/issues/17373

**Comment by guschmue** [comment]
That issue contains a couple of problems, like missing ops resulted in cross device copies and missing io-bindings resulted in a lot of cross device copies. I think we fix most of those. But this decoder issue has been in this too. Ie the io-bindings should have gained much more than they did.
Nasty issue, lots of gpu cycle available, kernel times look good, little cross device copy yet 2x slower than we want. Top of our list.
I can file a separate issue.

**Comment by guschmue** [comment]
https://github.com/microsoft/onnxruntime/issues/18754

**Comment by tarekziade** [comment]
@xenova I am curious to try. Do you have builds with WebGPU ? 

I've built onnxruntime with the jsep option but I am not entirely sure what are the spots to change in `transformers.js` - is it as simple as `executionProviders` to `ort.InferenceSession.create` ?

**Comment by DavidGOrtega** [comment]
Additionally another optimization should be done: STFT

**Comment by nmstoker** [comment]
For anyone coming here who didn't see it yet, there is webGPU support now thanks to Xenova's efforts [described here](https://huggingface.co/posts/Xenova/822789934095847)

Code in this branch: https://github.com/xenova/whisper-web/tree/experimental-webgpu

**Comment by guschmue** [comment]
> What about node.js? Will webGPU/GPU acceleration be available on server/desktop side w/o browser?

There is some experimental code path in [dawn](https://dawn.googlesource.com/dawn/+/refs/heads/main ) that one could use to make onnxruntime work with webgpu on node.js.
But we are not sure if people would use that path since onnxruntime-node already supports cuda and directml which is faster than webgpu.
