### ISSUE TITLE
Whisper Error: no available backend found

### ISSUE THREAD

**Issue by stinoga** [huggingface/transformers.js#1006]
### System Info

Transformers.js version: "@huggingface/transformers": "3.0.1"
Browser (if applicable): Chrome
Operating system: MacOS

### Environment/Platform

- [X] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

After upgrading from `3.0.0-alpha.9` to `3.0.1`, I'm getting the following error:
```
Uncaught (in promise) Error: no available backend found. ERR: [webgpu] RuntimeError: null function or function signature mismatch
```
I'm calling my model files from my own CDN, which is working fine on `3.0.0-alpha.9`. I can resolve the issue by removing the below `env` settings pointing to my CDN, and it loads fine from huggingface.

My first thought was maybe there was an update to `onnx-community/whisper-tiny.en`, which I pulled down from [here](https://huggingface.co/onnx-community/whisper-tiny.en/tree/main/onnx), however there haven't been any updates in the time I uploaded my model files (about a week ago). Has the huggingface CDN been updated with a version that I don't have?
```ts
import {
  AutoTokenizer,
  AutoProcessor,
  env,
  full,
  PreTrainedTokenizer,
  Processor,
  TextStreamer,
  WhisperForConditionalGeneration,
} from "@huggingface/transformers";

env.remoteHost =
  "MYCDN.com/shared/dictation/models/";
env.remotePathTemplate = "{model}/";

// Set location of .wasm files. Defaults to use a CDN.
if (env.backends?.onnx?.wasm) {
  env.backends.onnx.wasm.wasmPaths =
    "MYCDN.com/shared/dictation/";
}

const MAX_NEW_TOKENS = 64;

class AutomaticSpeechRecognitionPipeline {
  static model_id: string | null = null;
  static tokenizer: Promise<PreTrainedTokenizer> | null = null;
  static processor: Promise<Processor> | null = null;
  static model: Promise<any> | null = null;

  static async getInstance(
    progress_callback: Function | undefined = undefined
  ) {
    this.model_id = "onnx-community/whisper-tiny.en";

    this.tokenizer ??= AutoTokenizer.from_pretrained(this.model_id, {
      progress_callback: progress_callback || (() => {}),
    });
    this.processor ??= AutoProcessor.from_pretrained(this.model_id, {
      progress_callback: progress_callback || (() => {}),
    });

    this.model ??= WhisperForConditionalGeneration.from_pretrained(
      this.model_id,
      {
        dtype: {
          encoder_model: "fp32", // 'fp16' works too
          decoder_model_merged: "q4", // or 'fp32' ('fp16' is broken)
        },
        device: "webgpu",
        progress_callback: progress_callback || (() => {}),
      }
    );

    return Promise.all([this.tokenizer, this.processor, this.model]);
  }
}
```

### Reproduction

Load transformer.js v3.0.1 with model files from an external CDN that isn't huggingface.

**Comment by xenova** [comment]
> Im calling my model files from my own CDN, which is working fine on 3.0.0-alpha.9

Note that the WASM files change between versions, so please ensure that you have the correct [files](https://www.jsdelivr.com/package/npm/@huggingface/transformers) corresponding to the version you are using

**Comment by stinoga** [comment]
Ah! That's good to know! Closing.
