### ISSUE TITLE
Failed to initialize model onnx-community/whisper-base: Error: Failed to load model because protobuf parsing failed.

### ISSUE THREAD

**Issue by sbkobaidze** [huggingface/transformers.js#1025]
### System Info

    "@huggingface/transformers": "^3.0.2", 

Node -v - 20.0.0

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [X] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

I am trying to run model from local path but I get this error -- I tried loading different models but it presists.

` env.localModelPath =
              "./models";

            const instance = await pipeline(model.task, model.name, {
              progress_callback,
              local_files_only: true,
              dtype: "q8",
            });`
![image](https://github.com/user-attachments/assets/713a1d7d-d4a7-4b11-af14-ec9fe98f5f0a)

### Reproduction

1 .Download the Transfomers.js compatible model.
2. update the localModelPath
3. run the code with Node.js

**Comment by sbkobaidze** [comment]
As I understood it fails to access onnx/ dir

**Comment by sbkobaidze** [comment]
Ok, I needed to `git lfs pull` where models are located

**Comment by xenova** [comment]
Thanks for the update!

**Comment by nekomeowww** [comment]
In my case, this happens to me in development environment, it was because the version of `@huggingface/transformers.js` was updated, and deleting the cache dir inside the `node_modules` helped.

```shell
rm -rf node_modules/@huggingface/transformers/.cache/*
```
