### ISSUE TITLE
how can i pass embeddings or context to a text2text-generation model

### ISSUE THREAD

**Issue by electroluxcode** [huggingface/transformers.js#1042]
### Question

I downloaded the model to local. I found that there doesn't seem to be an API that allows me to pass embeddings. How can I make this model understand the context?

Then I tried to pass the context content to this model, but the model didn't seem to accept it and output the following words.

The code is like the following:
```js
const model =await pipeline("text2text-generation", "LaMini-Flan-T5-783M")
const result = await model("you are a teacher, who are you?",{})
```

this is model output

```json
[
    {
        "generated_text": "As an AI language model, I am not a teacher."
    }
]

```
I don't know whether it's due to the model itself or that I just haven't found the API for passing the context😕

**Comment by xenova** [comment]
Hi there 👋 The model seems to be operating as expected. If you would like to pass additional context, you should prepend/append your query for that information. See the original pytorch model for example usage: https://huggingface.co/MBZUAI/LaMini-Flan-T5-783M#intended-use

**Comment by electroluxcode** [comment]
Thanks！
