### ISSUE TITLE
PatchTSTModel, PatchTSTConfig, & Trainer

### ISSUE THREAD

**Issue by Datakunskap** [huggingface/transformers.js#1047]
### Feature request

Implementation of:
PatchTSTModel, PatchTSTConfig, & Trainer

Source:
https://github.com/huggingface/transformers/blob/v4.46.3/src/transformers/models/patchtst/modeling_patchtst.py#L1142

### Motivation

https://github.com/huggingface/transformers

### Your contribution

Submitting a PR

**Comment by xenova** [comment]
Opened PR [here](https://github.com/huggingface/transformers.js/pull/1048). Let me know if that works for you 👍

**Comment by xenova** [comment]
Sure thing! I've added them [here](https://github.com/huggingface/transformers.js/pull/1048/commits/db93aac8c3f3b735efdd8c4a364a8c2ac67765cf).

Example usage can be found [here](https://github.com/huggingface/transformers.js/pull/1048#issuecomment-2495133569).

Note for the config, you an simply do:
```js
import { AutoConfig } from '@huggingface/transformers';

const config = await AutoConfig.from_pretrained('hf-internal-testing/tiny-random-PatchTSTModel'); 
console.log(config);
```

**Comment by xenova** [comment]
Happy to help :)

**Comment by xenova** [comment]
Looks simple enough to add :) Feel free to open a new issue with the request, and if you can supply example input out output to check our implementation 👍
