### ISSUE TITLE
Module Not Found error ('./' import issue)

### ISSUE THREAD

**Issue by gurveervirk** [huggingface/transformers.js#1058]
### System Info

"dependencies": {
    "@huggingface/transformers": "^3.1.0",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  }

Basic CRA app

### Environment/Platform

- [X] Website/web-app
- [X] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

I am trying out the React App tutorial from [this](https://huggingface.co/docs/transformers.js/en/tutorials/react) link. I want to use transformers.js for a semantic search app but haven't been able to get it to work for the past couple of days.

I do not want to eject the app.

I have tried both @xenova/transformers and @huggingface/transformers and a number of versions of both.

Request you to let me know my options. 

Thanks!

### Reproduction

Just following [this](https://huggingface.co/docs/transformers.js/en/tutorials/react) tutorial.

**Comment by xenova** [comment]
Could you try using Vite instead of Create React App? Create React App has been deprecated since 2023 (see [here](https://www.freecodecamp.org/news/how-to-create-a-react-app-in-2024/#:~:text=In%202023%2C%20the%20Create%20React,a%20number%20of%20different%20alternatives.)).

**Comment by gurveervirk** [comment]
Got it! Thanks! 
Closing the issue.
