### ISSUE TITLE
ready event not exposed on ProgressInfo type

### ISSUE THREAD

**Issue by pelikhan** [huggingface/transformers.js#1064]
### System Info

transformers.js 3.1.0
typescript 5.7.2

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [X] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

The type definition of ProgressInfo does not expose the "ready" event that gets sent when the model is fully loaded.

### Reproduction

```ts
const generator = await pipeline('text-generation', 'Xenova/distilgpt2'. {
  progress_callback: ev => console.log(ev.status) // this will print "ready" when the model is loaded
});
const text = 'I enjoy walking with my cute dog,';
const output = await generator(text);
```

**Comment by xenova** [comment]
A follow-up PR to https://github.com/huggingface/transformers.js/pull/1034 would be great! cc @ocavue if you're able to take a look.

**Comment by emojiiii** [comment]
I guess what you want to find is "done"

**Comment by pelikhan** [comment]
> I guess what you want to find is "done"

"done" is emitted for each file and "ready" is emitted once all files are loaded. It's the last event.

**Comment by emojiiii** [comment]
> > I guess what you want to find is "done"
> 
> "done" is emitted for each file and "ready" is emitted once all files are loaded. It's the last event.

you are right. https://github.com/huggingface/transformers.js/blob/main/src/pipelines.js#L3267

**Comment by ocavue** [comment]
I've submitted a PR to fix this type issue.

**Comment by pelikhan** [comment]
ProgressInfo needs update too (https://github.com/huggingface/transformers.js/blob/2ee715c672e863edd317324b8feb8522f53342a7/src/utils/core.js#L13). Thanks!

**Comment by xenova** [comment]
Thanks @ocavue! 🔥 Also, that PR for a type checking github action would be great. Do note that there may be a lot of these warnings/errors, especially for undefined variables on configs (as they are specific to certain models).

**Comment by ocavue** [comment]
I submitted #1081 for type checking. Since `npm run build` will do type checking, I didn't add a new github action.
