### ISSUE TITLE
typecript类型推导太慢了

### ISSUE THREAD

**Issue by grasilife** [huggingface/transformers.js#1121]
### System Info

nodejs 22

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [X] Server-side (e.g., Node.js, Deno, Bun)
- [X] Desktop app (e.g., Electron)
- [X] Other (e.g., VSCode extension)

### Description

typecript类型推导太慢了

### Reproduction

demo:import { SummarizationServiceRunType } from "../main/servers/transformers/summarization";

**Comment by grasilife** [comment]
忽略吧,文件见层级太深就会导致类型推导太慢

**Comment by xenova** [comment]
Hi there 👋 We do not have `SummarizationServiceRunType`, so perhaps you are referring to a different library? Will close for now, but feel free to reopen if you have any other questions.
