### ISSUE TITLE
[Question] A WebGPU-accelerated ONNX inference run-time

### ISSUE THREAD

**Issue by ansarizafar** [huggingface/transformers.js#119]
Is it possible to use https://github.com/webonnx/wonnx with transformersjs?

**Comment by xenova** [comment]
At the moment, we are currently testing with the official onnxruntime-web implementation (https://github.com/microsoft/onnxruntime), which is still a work in progress.

So, wonnx is not currently supported, but if the interface is similar to onnxruntime-web, it would probably be easy to fork this project and use it instead. If someone would like to try, that could be awesome! And then I could always add wonnx as a supported backend.

**Comment by jlia0** [comment]
@xenova I would love to give it a try, I just converted instructor-base to ONNX format using your script, but I am not sure how to use the converted model with Transformer.js, onnxruntime-web or WONNX. For example,

`const outputs = await session.run({ input: inputTensor });`

How can I use the tokenizer and how do I process the input?

**Comment by xenova** [comment]
@jlia0 That would be awesome if you'd like to look into this!

I'd recommend looking at how we lay out the various pipeline function (https://github.com/xenova/transformers.js/blob/main/src/pipelines.js) to help you figure out what inputs to provide the models.

In the simplest case (e.g, for BERT), you'll just need to tokenize the inputs and then pass this to the model. Your code might look something like this:
```js
import { AutoTokenizer } from '@xenova/transformers';

let tokenizer = await AutoTokenizer.from_pretrained('bert-base-uncased');
let { input_ids } = await tokenizer('I love transformers!');
// Tensor {
//   data: BigInt64Array(6) [101n, 1045n, 2293n, 19081n, 999n, 102n],
//   dims: [1, 6],
//   type: 'int64',
//   size: 6,
// }
```

See https://huggingface.co/docs/transformers.js/api/tokenizers for more information.

You'll then pass this into `session.run`

**Comment by sandorkonya** [comment]
If i'm not mistaken, this question is somewhat related to [mine](https://github.com/xenova/transformers.js/issues/100), @jlia0 thank you bringing another possible solution in play.
