### ISSUE TITLE
[Feature request] Title goes here.

### ISSUE THREAD

**Issue by ghost** [huggingface/transformers.js#167]
**Name of the feature**
*In general, the feature you want added should be supported by HuggingFace's [transformers](https://github.com/huggingface/transformers) library:*
 - *If requesting a **model**, it must be listed [here](https://huggingface.co/docs/transformers/index#supported-models).*
 - *If requesting a **pipeline**, it must be listed [here](https://huggingface.co/docs/transformers/main_classes/pipelines).*
- *If requesting a **task**, it must be listed [here](https://huggingface.co/tasks).*

Support for all-MiniLM-L6-v2 and other semantic parsers with embeddings as output.

**Reason for request**
*Why is it important that we add this feature? What is your intended use case? Remember, we are more likely to add support for models/pipelines/tasks that are popular (e.g., many downloads), or contain functionality that does not exist (e.g., new input type).*

Semantic searching through documents.

**Additional context**
*Add any other context or screenshots about the feature request here.*

**Comment by xenova** [comment]
Hi there. Feature-extraction/embeddings are already supported by the library. Please refer to the [documentation](https://huggingface.co/docs/transformers.js/api/pipelines#module_pipelines.FeatureExtractionPipeline). In your case, you can use all-MiniLM-L6-v2 as follows:

```js
import { pipeline } from '@xenova/transformers';
let extractor = await pipeline('feature-extraction', 'Xenova/all-MiniLM-L6-v2');
let result = await extractor('This is a simple test.', { pooling: 'mean', normalize: true });
console.log(result);
// Tensor {
//     type: 'float32',
//     data: Float32Array [0.09094982594251633, -0.014774246141314507, ...],
//     dims: [1, 384]
// }
```
