### ISSUE TITLE
[Question] Chaining automatic-speech recognition tasks sometimes produces weird output?

### ISSUE THREAD

**Issue by funiel** [huggingface/transformers.js#228]
Hi! I'm using the automatic-speech recognition task with vanilla nodejs (20) for (almost) live transcription (after the person has stopped talking)

This is the setup I'm using as per the docs:

```
const multilingual = true;
const model = "base";
const modelName = `Xenova/whisper-${model}${multilingual ? "" : ".en"}`;

const transcriber = await pipeline("automatic-speech-recognition", modelName);

const wav = new wavefile.WaveFile();
wav.fromScratch(1, 48000, "32f", audioBuffer.getChannelData(0));

wav.toSampleRate(16000); // Whisper expects audio with a sampling rate of 16000

let audioData = wav.getSamples();
if (Array.isArray(audioData)) {
  audioData = audioData[0];
}

let output = await transcriber(audioData);
```

This code almost works perfectly (also verified the wav files by saving them locally)

But every once in a while the model seems to get stuck for a couple of seconds. I can't say if this is because I'm sending multiple requests to the pipe while there's still a task in progress (multiple speakers), or something else entirely. Sadly I don't think there's any documentation if the pipeline has a queue of some sort or if it just mangles the data weirdly.

The output will look like this even though the sound-snippet only contains a single "Ah...":

```
took 7.202248899996281s:  Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah... Ah...
```

or like this (no music was being played)

```
took 6.9480034999996425s:  [Music]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
```

Generation time is also much, much longer (normally under 1s with whisper-base, this is the main problem I'm facing)

Is this is a bug? I was thinking of working around the problem by canceling the operation if it takes longer than 2-3s if that's possible, but that'd just be the laziest workaround.
(something like `pipe.cancel();` or equivalent)

Or alternatively implementing a queue myself if it actually jumbles data when chaining tasks

Thanks so much in advance for any suggestions!

**Comment by xenova** [comment]
I recall this happening before when bad/mismatched quantization settings are used (as it sometimes depends on the hardware being run on). Since you're running server-side, you'd probably be able to run the unquantized model (quantized is default) with the following code:

```js
const transcriber = await pipeline("automatic-speech-recognition", modelName, { quantized: false });
```

Otherwise, if you're unable to run the unquantized model, I'd recommend playing around with quantization settings in the conversion script:

**Comment by funiel** [comment]
Hey thanks for the quick reply! I was actually already using the unquantized model, same output. I've done some more testing and it really does seem like this may be an issue with the model. This mostly happens when the input is something unintelligible (like just a "ts" sound or humming music) 

In my case this is probably happening because there might be some background bleed from another speaker, which is just unintelligible noise that then goes through the model and delays the output by a couple seconds (and returns weirdly long data)

So this might be a limitation of whisper I'm guessing? It usually works, but the occasional 12x delay is really weird to me.

**Comment by xenova** [comment]
> I was actually already using the unquantized model, same output

With this command?
```js
const transcriber = await pipeline("automatic-speech-recognition", modelName);
```

Because not specifying `{ quantized: false }` will default to use the quantized weights.

Could you try with the python library and see if you get the same result with that audio file? (You can maybe also send it here if you get a different result for debugging purposes).

You could maybe solve this problem by specifying some [generation options](https://huggingface.co/docs/transformers.js/api/utils/generation#module_utils/generation.GenerationConfig), like  `repetition_penalty` or `no_repeat_ngram_size`. For example:

```js
let output = await transcriber(audioData, {
repetition_penalty: 2,
no_repeat_ngram_size: 3,
});
```

Though, you should probably play around with these values.
