### ISSUE TITLE
GPU Acceleration to increase performance

### ISSUE THREAD

**Issue by milind-yadav** [huggingface/transformers.js#377]
Do we have any option to use GPU to increase performance of model loading and detection?
As currently in Object Detection it's taking around 10 seconds. If we want to do this on GPU, can we do that?

Running below lines through web worker, increases overall UI experience but not increases any performance.
```
const model = await pipeline("object-detection", "Xenova/detr-resnet-50");
const result = await model(img, { threshold: 0.9 });
```

Can we use GPU for that?

**Comment by felladrin** [comment]
We can't use GPU yet, but keep an eye on this other issue, which relates to the progress of WebGPU support:
- https://github.com/xenova/transformers.js/issues/73
