### ISSUE TITLE
Running tests locally fail

### ISSUE THREAD

**Issue by sroussey** [huggingface/transformers.js#491]
### Question

When I git clone to my Mac, and run tests, I get a lot of errors:

```
  ● Models › Loading different architecture types › gpt2 (GPT2Model)

    Could not locate file: "https://huggingface.co/gpt2/resolve/main/tokenizer_config.json".

      239 |
      240 |     const message = ERROR_MAPPING[status] ?? `Error (${status}) occurred while trying to load file`;
    > 241 |     throw Error(`${message}: "${remoteURL}".`);
          |           ^
      242 | }
      243 |
      244 | class FileCache {

      at handleError (src/utils/hub.js:241:11)
      at getModelFile (src/utils/hub.js:474:24)
      at getModelJSON (src/utils/hub.js:575:18)
          at async Promise.all (index 1)
      at loadTokenizer (src/tokenizers.js:61:16)
      at Function.from_pretrained (src/tokenizers.js:2465:20)
      at Object.<anonymous> (tests/models.test.js:61:37)
```

And indeed, a lot of files don't actually exist, like in this case:

https://huggingface.co/gpt2/resolve/main/tokenizer_config.json

But I don't see this in the logs for your github actions, so i am confused.

**Comment by sroussey** [comment]
Oh, I see what you did. Local tests are.... optimistic.

Perhaps a better way would be to try optimistic, and if it fails, then use your copies?

**Comment by sroussey** [comment]
BTW: you can have github actions cache your `.cache` folder, but you would need a decent cache key.

**Comment by xenova** [comment]
Hi there :wave: This behaviour was taken over from a very early version of the project, where I would just name the models the same as they are on the HF Hub, and store the model weights under my HF account. A change was needed to run with github actions, so I introduced the `TESTING_REMOTELY` environment variable to link to models under the [Xenova](https://huggingface.co/Xenova) account on HF. So, if you want to test locally, you can set `TESTING_REMOTELY=1` (a bit confusing I guess), which will use the web-ready versions.

A follow-up PR will be ideal to improve this.
