### ISSUE TITLE
YOLOS model extremely slow

### ISSUE THREAD

**Issue by tarekziade** [huggingface/transformers.js#533]
### System Info

latest wasm version

### Environment/Platform

- [x] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

I am trying to run https://huggingface.co/hustvl/yolos-tiny using a quantized version (similar to Xenova/yolos-tiny) and it works by using the `object-detection` pipeline but it is extremely slow. 

An image that gets infered using the same model in transformers python takes around 15 seconds on my M1. The python version takes 190 ms.

I tried to run the web dev tool, and the curlpit is in the ONNX runtime at wasm-function[10863] @ ort-wasm-simd.wasm:0x801bfa but I don't have the debug symbols so it's kind of useless...

Is there a way to force transformers.js to run with a debug version of the ort runtime?

### Reproduction

Runs the object detection demo at https://xenova.github.io/transformers.js/, swap the detr-resnet model with the yolo-tiny

**Comment by xenova** [comment]
Can you try using the unquantized version? Done by specifying:
```js
const pipe = await pipeline('task', 'model', { quantized: false });
```

**Comment by tarekziade** [comment]
It's slightly faster, 
- non quantized : 15s  
- quantized: 20s
-
Maybe it's the image encoding step, I will try to measure each step

**Comment by xenova** [comment]
This might just be a limitation of onnxruntime-web's WASM execution provider, and can be fixed with the new WebGPU execution provider (coming soon).

@fs-eire @guschmue might be able to do more in-depth profiling.
