### ISSUE TITLE
Sharpe Linux-x86

### ISSUE THREAD

**Issue by Damibu** [huggingface/transformers.js#541]
### Question

Hi,

Firstly, many thanks for all your work.

My use case is to generate sentence embeddings for semantic matching. I develop on Mac but deploy to AWS Lambda.

Your package runs fine out the box on my Mac but fails to load Sharp on Lambda. I spent a couple of days trying lots of different things (fetching and building for Linux x86 and moving files around), but I never got it to work. In the end I removed the dependency on Sharp and it worked.

All's well, at present, but I do have a requirement in the future to embed images.

Sorry, I realise this may be more of a NPM issue (or more likely my knowledge of it), but any help would be appreciated.

Thanks
Dave

**Comment by Damibu** [comment]
Great, many thanks

**Comment by michaelsteenkamp** [comment]
@Damibu How did you remove the dependency on sharp? Running into the same AWS Lambda issue!
