### ISSUE TITLE
Support stopping criteria for sequence generation

### ISSUE THREAD

**Issue by hans00** [huggingface/transformers.js#786]
### Feature request

ref: https://github.com/huggingface/transformers/blob/main/src/transformers/generation/stopping_criteria.py

### Motivation

This will helpful for abstraction EOS stopping, max length stopping etc.
And could support stop words.

### Your contribution

I'll implement it if I have time.

**Comment by xenova** [comment]
Hi there 👋 This has been added to v3 (see [here](https://github.com/xenova/transformers.js/blob/v3/src/generation/stopping_criteria.js)).
