### ISSUE TITLE
Next.js example breaks with v3

### ISSUE THREAD

**Issue by stinoga** [huggingface/transformers.js#911]
### Question

Are there steps documented anywhere for running V3 in your app? I'm trying to test it out via these steps:

1. Pointing to the alpha in my `package.json`: `"@huggingface/transformers": "^3.0.0-alpha.10",`
2. `npm i`
3. `cd node_modules/@hugginface/transformers && npm i`
4. copy the [webpack.config.js](https://github.com/xenova/transformers.js/blob/main/webpack.config.js) from the repo into the node_modules/@hugginface/transformers dir.
5. `npm run build` in node_modules/@hugginface/transformers dir.

I then run my app, and get the following error:
```
ERROR in ../../node_modules/@huggingface/transformers/dist/transformers.js 42256:34-64
Module not found: Error: Can't resolve './' in '/node_modules/@huggingface/transformers/dist'
webpack compiled with 1 error
```

Thanks, I'm excited to test out the latest and greatest!

**Comment by nnennajohn** [comment]
+1 on this error. Also in 3.0.0-alpha.13

<img width="923" alt="Screenshot 2024-08-29 at 4 46 08 PM" src="https://github.com/user-attachments/assets/7a34ad42-5928-4f50-9357-a29610a657fb">
<img width="912" alt="Screenshot 2024-08-29 at 4 42 32 PM" src="https://github.com/user-attachments/assets/f904c10d-5a92-4837-8de3-93554ea479ff">

**Comment by xenova** [comment]
Hi there! 👋 What environment are you running in (OS, build tool, browser, node)? 👀 I haven't seen an error like this before 🤔 Can you share your webpack config?

**Comment by stinoga** [comment]
> Hi there! 👋 What environment are you running in (OS, build tool, browser, node)? 👀 I haven't seen an error like this before 🤔 Can you share your webpack config?

Sure can!

OS: Sonoma 14.6.1
Build tool: Lerna
Browser: Chrome
Node: v22.3.0

Regarding webpack config, we aren't using webpack. The config I coped into transformers dir was from the [main branch](https://github.com/xenova/transformers.js/blob/main/webpack.config.js).

**Comment by ChangJi** [comment]
example error +1
1. cd examples/webgpu-whisper/
2. pnpm install
3. pnpm build

error during build:
[vite:worker-import-meta-url] Failed to resolve entry for package "@xenova/transformers". The package may have incorrect main/module/exports specified in its package.json.

OS: Sonoma 14.6.1
node v21.4.0

**Comment by legut2** [comment]
I ran into this issue when using webpack on `worker.js` into `worker.bundle.js`. `@xenova/transformers` on `2.17.2` worked just fine. I tried upgrading to `@huggingface/transformers` on `3.0.0-alpha.14`.

I'm on:
macOS: 14.3.1 (23D60)
Node: v22.7.0
Browser: Firefox

With the following import statement, it works well
```js
import { pipeline } from '@xenova/transformers';
```
alongside this webpack.config.js file:
```js
const path = require('path');

module.exports = {
  entry: './static/images/js/worker.js',
  output: {
    filename: 'worker.bundle.js',
    path: path.resolve(__dirname, 'static/images/js'),
  },
  mode: 'production',
  target: 'webworker',
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
          },
        },
      },
    ],
  },
  resolve: {
    extensions: ['.js'],
  },
};
```
However, it doesn't work with: 
```js
import { pipeline, AutoProcessor, Swin2SRForImageSuperResolution, RawImage } from '@huggingface/transformers';
```

**Comment by sebastien-lempens** [comment]
I ran into the same issue, but I’ve figured out the solution! 
Just add the following to your Webpack configuration file (or Next.js configuration in my case):
`config.resolve.alias['@huggingface/transformers'] = path.resolve(__dirname, 'node_modules/@huggingface/transformers');`

It works like a charm right now :)

**Comment by GaLambert** [comment]
+1, @sebastien-lempens thanks for the solution!

**Comment by stinoga** [comment]
> The error happens only with version [3.0.0-alpha.10](https://www.npmjs.com/package/@huggingface/transformers/v/3.0.0-alpha.10) or newer. [3.0.0-alpha.9](https://www.npmjs.com/package/@huggingface/transformers/v/3.0.0-alpha.9) works fine for me. Was testing with webpack and in this env:
> 
> OS: Sonoma 14.6.1 Browser: Chrome Node: v22.3.0

This was the temporary solve for me. Since we are using Lerna with CRA, the webpack alias didn't fix things.

Not sure what happened between versions alpha 9 and 10, but that's where this issue starts showing up.

**Comment by nnennajohn** [comment]
> I ran into the same issue, but I’ve figured out the solution! Just add the following to your Webpack configuration file (or Next.js configuration in my case):
> 
> ```js
> webpack(config, { isServer }) {
> 	config.resolve.alias['@huggingface/transformers'] = path.resolve(__dirname, 'node_modules/@huggingface/transformers');
>         .... 
> 	return config;
> 	}
> ```
> 
> It works like a charm now :)

@jpcoder2 did you try this? Worked for me

**Comment by SrilalS** [comment]
> Any word on fix this issue in the most current version?

Still the same as of ^3.0.0-alpha.19 but the @sebastien-lempens 's solution works for me.

**Comment by laurislopata** [comment]
Are there any updates regarding this?

**Comment by xenova** [comment]
@laurislopata We're working on fixing this, as well as creating a Next.js example project which should serve as a basis for others to build on.

Which version of Next.js are you using? Next.js v15 just came out, and from initial testing, may not need the workaround shown above.

**Comment by xenova** [comment]
I might have found a better solution (tested in Next.js v15):
```js
const nextConfig = {
  output: "standalone",
  // https://nextjs.org/docs/app/api-reference/next-config-js/serverExternalPackages
  serverExternalPackages: ["@huggingface/transformers"],
};
```

Let me know if that fixes it!

---

Demo: https://huggingface.co/spaces/webml-community/next-server-template
Source code: https://github.com/huggingface/transformers.js-examples/tree/main/next-server

**Comment by stinoga** [comment]
> I might have found a better solution (tested in Next.js v15):
> 
> ```js
> const nextConfig = {
>   output: "standalone",
>   // https://nextjs.org/docs/app/api-reference/next-config-js/serverExternalPackages
>   serverExternalPackages: ["@huggingface/transformers"],
> };
> ```
> 
> Let me know if that fixes it!
> 
> Demo: https://huggingface.co/spaces/webml-community/next-server-template Source code: https://github.com/huggingface/transformers.js-examples/tree/main/next-server

Is there an equivalent solve for a Lerna/CRA setup? I can't add the webpack fix above, as CRA won't recognize it unless we eject CRA, which would be a large undertaking. I'd like to try out the official 3.0.0 version, but I'm still getting the original error posted above.
```

**Comment by stinoga** [comment]
I ended up ejecting create-react-app to fix this issue. For anyone that goes that route, ejecting puts all config, including webpack, into a config dir. I fixed the issue by adding this alias:
```js
"@huggingface/transformers": path.resolve(
  __dirname.replace("/config", ""),
  "node_modules/@huggingface/transformers"
),
```

I'm going to close this out, as my original issue is resolved.

**Comment by djaffer** [comment]
This issue is till there. Had to go back to @xenova/transformers.

**Comment by 2010b9** [comment]
> I ended up ejecting create-react-app to fix this issue. For anyone that goes that route, ejecting puts all config, including webpack, into a config dir. I fixed the issue by adding this alias:
> 
> ```js
> "@huggingface/transformers": path.resolve(
>   __dirname.replace("/config", ""),
>   "node_modules/@huggingface/transformers"
> ),
> ```
> 
> I'm going to close this out, as my original issue is resolved.

This solved it for me! Thank you :)

**Comment by yeus** [comment]
this also works with vue3/webpack! thank you...

**Comment by djaffer** [comment]
still getting this error.

**Comment by xenova** [comment]
@djaffer which build tool are you using with react? I have tested and it works with Vite. Are you perhaps using create-react-app or parcel?

**Comment by djaffer** [comment]
React app with react scripts. It uses webpack.

**Comment by xenova** [comment]
@Nithur-M could you try v3.1.1? It includes https://github.com/microsoft/onnxruntime/pull/23257, which aims to solve this issue.

**Comment by stinoga** [comment]
> I am using a react application build with create-react-app. However I am also facing the same issue. It does not use any webpack config explicitly. How can I apply the workaround mentioned here in a pure React app build using create-react-app?

I ejected `creat-react-app` to resolve this issue. See https://github.com/huggingface/transformers.js/issues/911#issuecomment-2452106694

**Comment by pradip-interra** [comment]
@stinoga where you put this ejecting code? My app is using create-react-app, it does not have a webpack config file. So where should I put this ejecting code? If you can please suggest.

**Comment by djaffer** [comment]
for react I ended up with this. Too many issues not worth the time. import { pipeline } from 'https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.3.1';

**Comment by fs-eire** [comment]
After some investigation and code changes, I think [this PR](https://github.com/huggingface/transformers.js/pull/1161) should have fixed the export problems.

I checked both `create-next-app` and `create-react-app`:
- `create-next-app`: works, but need adding `serverExternalPackages: ["@huggingface/transformers"],` in next config (mentioned in https://github.com/huggingface/transformers.js/issues/911#issuecomment-2430912760)
- `create-react-app`: works out-of-the-box.

**Comment by Emmaccen** [comment]
> I ran into the same issue, but I’ve figured out the solution! Just add the following to your Webpack configuration file (or Next.js configuration in my case):
> 
> webpack(config, { isServer }) {
> 	config.resolve.alias['@huggingface/transformers'] = path.resolve(__dirname, 'node_modules/@huggingface/transformers');
>         .... 
> 	return config;
> 	}
> It works like a charm now :)

If you ever run into other issues even after doing the above quoted solution (https://github.com/huggingface/transformers.js/issues/911#issuecomment-2329440874)  by @sebastien-lempens, you might need to add one more if you haven't already

`next.config.(js,mjs,ts)`
```
import * as path from 'path';
const __dirname = path.resolve();

/** @type {import('next').NextConfig} */
const nextConfig = {

+ webpack: (config) => {
+     // See https://webpack.js.org/configuration/resolve/#resolvealias
+    config.resolve.alias = {
+       ...config.resolve.alias,
+       sharp$: false,
+      'onnxruntime-node$': false,
+   };

    config.resolve.alias['@huggingface/transformers'] = path.resolve(
      __dirname,
      'node_modules/@huggingface/transformers',
    );

return config

}

}
```
Also see References

* https://huggingface.co/docs/transformers.js/tutorials/next
* https://huggingface.co/docs/transformers.js/tutorials/vanilla-js
* https://huggingface.co/docs/transformers.js/tutorials/react

Thanks @sebastien-lempens. You saved me a week of headaches
