### ISSUE TITLE
[v3.x] Cannot load whisper-v3-large-turbo 

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [huggingface/transformers.js#989]
### System Info

3.x

### Environment/Platform

- [X] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

Can't create a session. ERROR_CODE: 1, ERROR_MESSAGE: Deserialize tensor onnx::MatMul_4069 failed.Failed to load external data file ""encoder_model.onnx_data"", error: Module.MountedFiles is not available.

### Reproduction

pipeline(
        'automatic-speech-recognition',
        'onnx-community/whisper-large-v3-turbo',
        {  progress_callback,device:"webgpu" },
      )

**Comment by xenova** [comment]
Hi there 👋 There are 2 ways to fix this:

1. Use a dtype which is < 2GB:
    ```js
    pipeline(
        'automatic-speech-recognition',
        'onnx-community/whisper-large-v3-turbo',
        {
            progress_callback,
            device:"webgpu",
            dtype: {
                encoder_model: "fp16",
                decoder_model_merged: "q4",
            }
        },
    )
    ```

2. Use external data format for the fp32 encoder (which is > 2GB):
    ```js
    pipeline(
        'automatic-speech-recognition',
        'onnx-community/whisper-large-v3-turbo',
        {
            progress_callback,
            device:"webgpu",
            use_external_data_format: {
                encoder_model: true,
                decoder_model_merged: false,
            }
        },
    )
    ```

---

Let me know if that helps!

**Comment by liuhuapiaoyuan** [comment]
same error...

**Comment by liuhuapiaoyuan** [comment]
``
pipeline(
'automatic-speech-recognition'
onnx-community/whisper-large-v3-turbo
{
progress_callback
device: "webgpu"
dtype: {
encoder_model: "fp16"
"decoder_model_merged: \"q4\"",
}
}
)
```

This can solve the problem
