### ISSUE TITLE
Add support for moonshine ASR models

### ISSUE THREAD

**Issue by bil-ash** [huggingface/transformers.js#990]
### Model description

Please add support for [moonshine](https://huggingface.co/UsefulSensors/moonshine) ASR models. The recent [github commit](https://github.com/usefulsensors/moonshine/commit/888f72910edb43ae3aa4d88fb86acd3e983399b9) adds support for onnx(python), so I guess porting to js won't take much effort. However, there is no mention about transformers usage.

This model is quite good for in-browser usage scenario since it is quite small and claims to use RAM proportional to length of audio.

### Prerequisites

- [ ] The model is supported in Transformers (i.e., listed [here](https://huggingface.co/docs/transformers/index#supported-models-and-frameworks))
- [X] The model can be exported to ONNX with Optimum (i.e., listed [here](https://huggingface.co/docs/optimum/main/en/exporters/onnx/overview))

### Your contribution

None

**Comment by evmaki** [comment]
Hi, Evan from Useful Sensors/Moonshine here. Just letting you know this is on our radar. We're working on [Transformers support](https://github.com/huggingface/transformers/issues/34474) right now, and we (internally) have our current ONNX models running in the browser with `onnxruntime-web`. Shouldn't be _too_ difficult to get support added to transformers.js from there.

**Comment by bil-ash** [comment]
> Hi, Evan from Useful Sensors/Moonshine here. Just letting you know this is on our radar. We're working on [Transformers support](https://github.com/huggingface/transformers/issues/34474) right now, and we (internally) have our current ONNX models running in the browser with `onnxruntime-web`. Shouldn't be _too_ difficult to get support added to transformers.js from there.

@evmaki Not related to this issue, but I am also eagerly waiting for the ability to finetune for supporting a new language.

**Comment by xenova** [comment]
> Hi, Evan from Useful Sensors/Moonshine here. Just letting you know this is on our radar. We're working on https://github.com/huggingface/transformers/issues/34474 right now, and we (internally) have our current ONNX models running in the browser with onnxruntime-web. Shouldn't be too difficult to get support added to transformers.js from there.

@evmaki Great to hear! I have been following the ONNX support and it looks like a great start! One minor issue is that you currently export two versions of the decoder (w/ and w/o PKVs), leading to major weight duplication (more of a problem when running in the browser since we load the decoder twice).

We were able to solve this in Optimum by adding an If node to the graph and then choosing which path to take based on whether the past key values are provided. See [here](https://huggingface.co/Xenova/whisper-tiny.en/blob/main/onnx/decoder_model_merged.onnx) for an example. And [here](https://github.com/huggingface/optimum/blob/2e637be5d6b3e15c2b300130599bcec0f3e12ec8/optimum/onnx/graph_transformations.py#L197) is the code used to merge the two decoders.

I was experimenting with your codebase to pass zero-sized tensors as input, but I get gibberish output.

Either way, once we have `transformers` support, I expect this to be much easier to convert (since the input/output signatures should be similar to whisper).

**Comment by xenova** [comment]
I have some exciting news: we've got a working version of moonshine-tiny (See PR: https://github.com/huggingface/transformers.js/pull/1099) which offers numerous benefits over the [original/upstream ONNX implementation](https://github.com/usefulsensors/moonshine/tree/main/moonshine-onnx):
1. Huge reduction in model size (285MB &rarr; 109MB), with zero quality loss:
  Original = 285MB ([7](https://huggingface.co/spaces/UsefulSensors/moonshine-web/blob/main/moonshine/tiny/preprocess.onnx)+[30](https://huggingface.co/spaces/UsefulSensors/moonshine-web/blob/main/moonshine/tiny/encode.onnx)+[120](https://huggingface.co/spaces/UsefulSensors/moonshine-web/blob/main/moonshine/tiny/cached_decode.onnx)+[128](https://huggingface.co/spaces/UsefulSensors/moonshine-web/blob/main/moonshine/tiny/uncached_decode.onnx)) at fp32
  ![image](https://github.com/user-attachments/assets/f6bd8dc6-400c-492c-9bf1-76ce81c07002)
  Ours = 109MB ([31](https://huggingface.co/onnx-community/moonshine-tiny-ONNX/blob/main/onnx/encoder_model.onnx) + [78](https://huggingface.co/onnx-community/moonshine-tiny-ONNX/blob/main/onnx/decoder_model_merged.onnx)) at fp32

    This is due to the following optimizations:
    - Deduplicated tied weights (the [original model](https://huggingface.co/UsefulSensors/moonshine-tiny) also suffers from this problem, which is why it displays as 46.5M params instead of the correct 27M params)
    - Merging the two decoders (w/ and w/o PKV inputs) into a single graph

2. Multiple quantization support: int8/uint8, q4, fp16, q4f16. We are facing an issue with fp16/q4f16 decoder (cc @guschmue), but all other quantizations work. At q4 quantization, which still works pretty well, the model size is further reduced to 55MB ([44.7](https://huggingface.co/onnx-community/moonshine-tiny-ONNX/blob/main/onnx/decoder_model_merged_q4.onnx)+[10.4](https://huggingface.co/onnx-community/moonshine-tiny-ONNX/blob/main/onnx/encoder_model_q4.onnx))


cc @evmaki - I think these benefits can also be upstreamed, and I'd be happy to make a PR if you'd like! 🤗

**Comment by evmaki** [comment]
@xenova That's fantastic! Please do open a PR – excited to take a look!

**Comment by fidoriel** [comment]
Has the merge conversion been changed in the transformers conversion script?

**Comment by fidoriel** [comment]
> Has the merge conversion been changed in the transformers conversion script?

got it working with 
`python3 -m scripts.convert --quantize --model_id id --task automatic-speech-recognition-with-past`

used latest version transformersjs 43622374f44c393e24228ebd8594369e96a13bb5

```
huggingface_hub
transformers[torch]==4.52.4
onnxruntime==1.20.1
git+https://github.com/huggingface/optimum.git@85376e337681b1db6aa9752cc4f592b56eedb85e
tqdm==4.67.1
onnxslim==0.1.56
```
